### PR TITLE
Fix timing issue with `rly tx relay-packets`

### PR DESCRIPTION
**Pull request by jackzampolin**

### CODE REVIEW

**Comment by jackzampolin** [comment]
First commit fixed some things. Second commit appears not working rn

**Review by faddat — COMMENTED** [review]
presently just following.

**Comment by jackzampolin** [comment]
Core idea here: query height once at the top of the callstack and pass height down through the call stack to avoid mismatches.

**Comment by faddat** [comment]
thanks for the clarifying info.

**Comment by jackzampolin** [comment]
closing this in favor of other work

**Pull request closed without merging**
